# Site settings
title: waiworinao ★ notes by arvid andersson
email: arvid.andersson@gmail.com
description: ""
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.arvidandersson.se" # the base hostname & protocol for your site
twitter_username: arvid_a
github_username:  arvida

permalink: /:year/:month/:day/:title
# Build settings
markdown: kramdown
defaults:
-
  scope:
    path: "" # an empty string here means all files in the project
  values:
    layout: "post"
